#!/usr/bin/env python3
"""Generate a HUB's cross-demand memory index from observation frontmatter.

Progressive disclosure, markdown-first (D3): observation details live one-per-file
under `<hub>/memory/<slug>.md`; this builds the compact index `<hub>/005-memory.md`
that a session scans first, loading a detail file JIT by id. The index is
generated **deterministically** from frontmatter (reproducible, drift-checkable);
only the observation content is distilled (and human-confirmed) — see
`rules/common/memory-policy.md`.
"""

import argparse
import sys
from pathlib import Path

REQUIRED = ("id", "type", "title", "date")
TYPE_ICON = {"decision": "🔵", "gotcha": "🔴"}


def parse_frontmatter(path):
    """Parse a flat ``key: value`` YAML frontmatter block into a dict."""
    lines = path.read_text(encoding="utf-8-sig").splitlines()
    if not lines or lines[0].strip() != "---":
        raise SystemExit(f"Missing frontmatter: {path}")
    data = {}
    for line in lines[1:]:
        if line.strip() == "---":
            return data
        if not line.strip() or ":" not in line:
            continue
        key, value = line.split(":", 1)
        data[key.strip().lower()] = value.strip()
    raise SystemExit(f"Unclosed frontmatter: {path}")


def list_observations(hub):
    memory_dir = hub / "memory"
    if not memory_dir.exists():
        return []
    return sorted(p for p in memory_dir.glob("*.md") if p.name != "README.md")


def render_index(hub):
    rows = []
    for path in list_observations(hub):
        data = parse_frontmatter(path)
        missing = [k for k in REQUIRED if not data.get(k)]
        if missing:
            raise SystemExit(f"{path} missing frontmatter keys: {', '.join(missing)}")
        icon = TYPE_ICON.get(data["type"].lower(), "⚪")
        rows.append([
            f"`{data['id']}`",
            f"{icon} {data['type']}",
            data["title"],
            data.get("source-demand", "—"),
            data["date"],
            f"[memory/{path.name}](memory/{path.name})",
        ])

    lines = [
        "# Memory Index",
        "",
        "> Generated by `scripts/*/workflow/generate-memory-index.*` from each "
        "observation's frontmatter. Do not edit the table by hand.",
        "",
        "Compact, cross-demand memory. Scan this index first; load an observation's "
        "file JIT by id only when its trigger/tags match the current demand. "
        "Observations are **pointers, not authority** — open the original artifact "
        "before deciding or editing (`rules/common/memory-policy.md`).",
        "",
        "## Legend",
        "🔵 decision · 🔴 gotcha",
        "",
        "## Observations",
        "| Id | Type | Title | Demand | Date | Link |",
        "|---|---|---|---|---|---|",
    ]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    lines.extend([
        "",
        "## Rule",
        "Load only the observation whose trigger/tags match the active demand — "
        "never the whole set. New observations are proposed by Alfred at demand "
        "close and confirmed by a human (additive, non-authoritative).",
    ])
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", "-Root", dest="root", default=".",
                        help="HUB directory containing memory/ and the index")
    parser.add_argument("--index-name", dest="index_name", default="005-memory.md")
    parser.add_argument("--check", "-Check", action="store_true", dest="check")
    args = parser.parse_args()

    hub = Path(args.root).resolve()
    content = render_index(hub)
    index_path = hub / args.index_name
    current = index_path.read_text(encoding="utf-8") if index_path.exists() else ""
    if args.check:
        if current != content:
            raise SystemExit(f"Memory index drift: regenerate {index_path}")
        print(f"OK memory index {index_path}")
        return 0
    index_path.write_text(content, encoding="utf-8", newline="\n")
    print(f"Wrote {index_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
