param(
  [string]$Root = "."
)

$ErrorActionPreference = "Stop"
$rootPath = Resolve-Path -LiteralPath $Root
$registryPath = Join-Path $rootPath "skills/skills.md"

if (-not (Test-Path -LiteralPath $registryPath)) {
  throw "Missing skills registry: $registryPath"
}

$requiredFrontmatter = @(
  "name",
  "description",
  "trigger",
  "sections_to_load"
)

$requiredBodySections = @(
  "purpose",
  "inputs",
  "expected output"
)

$removedBodySections = @(
  "name",
  "trigger",
  "link",
  "sections to load"
)

function Read-Frontmatter {
  param([string]$Path)

  $lines = Get-Content -LiteralPath $Path
  if ($lines.Count -eq 0 -or $lines[0].Trim() -ne "---") {
    throw "Skill $(Split-Path -Leaf $Path) is missing frontmatter"
  }

  $end = -1
  for ($i = 1; $i -lt $lines.Count; $i += 1) {
    if ($lines[$i].Trim() -eq "---") {
      $end = $i
      break
    }
  }
  if ($end -lt 0) {
    throw "Skill $(Split-Path -Leaf $Path) has unclosed frontmatter"
  }

  $data = @{}
  $current = $null
  for ($i = 1; $i -lt $end; $i += 1) {
    $line = $lines[$i]
    if ($line -match "^\s{2}-\s+(.*)$") {
      if (-not $current) {
        throw "Skill $(Split-Path -Leaf $Path) has list item without key"
      }
      if (-not ($data[$current] -is [System.Collections.ArrayList])) {
        $data[$current] = [System.Collections.ArrayList]@()
      }
      [void]$data[$current].Add($Matches[1].Trim())
      continue
    }
    if ($line -match "^([A-Za-z0-9_-]+):\s*(.*)$") {
      $current = $Matches[1]
      $value = $Matches[2].Trim()
      if ($value.Length -eq 0) {
        $data[$current] = [System.Collections.ArrayList]@()
      } else {
        $data[$current] = $value
      }
    }
  }

  return $data
}

$registryContent = Get-Content -LiteralPath $registryPath -Raw
if ($registryContent -notmatch "Generated by ``scripts/\*/workflow/generate-registry\.\*``") {
  throw "skills/skills.md must be generated by generate-registry"
}

$skillFiles = Get-ChildItem -Path (Join-Path $rootPath "skills") -Filter "*.md" |
  Where-Object { $_.Name -ne "skills.md" } |
  Sort-Object FullName

if ($skillFiles.Count -eq 0) {
  throw "No skill files found."
}

foreach ($skillPath in $skillFiles) {
  $data = Read-Frontmatter -Path $skillPath.FullName
  $name = if ($data.ContainsKey("name")) { $data["name"] } else { $skillPath.BaseName }
  $missing = @()
  foreach ($key in $requiredFrontmatter) {
    if (-not $data.ContainsKey($key)) {
      $missing += $key
    }
  }
  if ($missing.Count -gt 0) {
    throw "Skill $name missing frontmatter keys: $($missing -join ', ')"
  }
  if (-not ($data["sections_to_load"] -is [System.Collections.IEnumerable]) -or $data["sections_to_load"].Count -eq 0) {
    throw "Skill $name frontmatter sections_to_load must be a non-empty list"
  }

  $content = Get-Content -LiteralPath $skillPath.FullName -Raw
  foreach ($section in $requiredBodySections) {
    $escaped = [regex]::Escape($section)
    if ($content -notmatch "(?im)^##\s+$escaped\s*$") {
      throw "Skill $name is missing required section: $section"
    }
  }
  foreach ($section in $removedBodySections) {
    $escaped = [regex]::Escape($section)
    if ($content -match "(?im)^##\s+$escaped\s*$") {
      throw "Skill $name still carries duplicated metadata section: $section"
    }
  }

  Write-Output "OK skill $name"
}

Write-Output "Skills registry validation completed."
