#!/usr/bin/env python3
"""Validate the Alfred skills registry."""

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from _common import read_lines, read_text  # noqa: E402

REQUIRED_FRONTMATTER = [
    "name",
    "description",
    "trigger",
    "sections_to_load",
]

REQUIRED_BODY_SECTIONS = [
    "purpose",
    "inputs",
    "expected output",
]

REMOVED_BODY_SECTIONS = [
    "name",
    "trigger",
    "link",
    "sections to load",
]


def parse_frontmatter(path):
    text = read_text(path)
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise SystemExit(f"Skill {path.name} is missing frontmatter")

    end = None
    for index, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end = index
            break
    if end is None:
        raise SystemExit(f"Skill {path.name} has unclosed frontmatter")

    data = {}
    current = None
    for raw in lines[1:end]:
        if raw.startswith("  - "):
            if current is None:
                raise SystemExit(f"Skill {path.name} has list item without key")
            data.setdefault(current, []).append(raw[4:].strip())
            continue
        match = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", raw)
        if match:
            current = match.group(1)
            value = match.group(2).strip()
            data[current] = value if value else []
    return data


def assert_section(content, section, name):
    pattern = r"(?im)^##\s+" + re.escape(section) + r"\s*$"
    if not re.search(pattern, content):
        raise SystemExit(f"Skill {name} is missing required section: {section}")


def assert_absent_section(content, section, name):
    pattern = r"(?im)^##\s+" + re.escape(section) + r"\s*$"
    if re.search(pattern, content):
        raise SystemExit(f"Skill {name} still carries duplicated metadata section: {section}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", "-Root", dest="root", default=".")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    registry = root / "skills" / "skills.md"
    if not registry.exists():
        raise SystemExit(f"Missing skills registry: {registry}")

    registry_text = read_text(registry)
    if "Generated by `scripts/*/workflow/generate-registry.*`" not in registry_text:
        raise SystemExit("skills/skills.md must be generated by generate-registry")

    skills = sorted((root / "skills").glob("*/SKILL.md"))
    if not skills:
        raise SystemExit("No skill files found.")

    for skill_path in skills:
        data = parse_frontmatter(skill_path)
        missing = [key for key in REQUIRED_FRONTMATTER if key not in data]
        name = data.get("name", skill_path.parent.name)
        if missing:
            raise SystemExit(f"Skill {name} missing frontmatter keys: {', '.join(missing)}")
        if not isinstance(data.get("sections_to_load"), list) or not data["sections_to_load"]:
            raise SystemExit(f"Skill {name} frontmatter sections_to_load must be a non-empty list")
        content = read_text(skill_path)
        for section in REQUIRED_BODY_SECTIONS:
            assert_section(content, section, name)
        for section in REMOVED_BODY_SECTIONS:
            assert_absent_section(content, section, name)
        print(f"OK skill {name}")

    print("Skills registry validation completed.")


if __name__ == "__main__":
    main()
